### ISSUE TITLE
Feature Request: Support returning IANA string, such as "America/New_York" as the Timezone

### ISSUE THREAD

**Issue by benshamsian** [wcg-developers/phone-number-to-timezone#7]
First I like to say thank you for building and maintaining this package. 

We are trying to get the Timezone based on a phone number and use it with [Luxon](https://moment.github.io/luxon/docs/manual/zones.html) DateTime library.

Luxon works a lot better when you use it with IANA timezone strings specially when you are doing DateTime calculations that go across Daylight Saving Time changes.  Although your library supports the { zone_display: 'name' } option it will return Named Offset such as "EST" rather than IANA string such as "America/New_York".  Luxon does not work with Named Offsets when used on the server side in Node.  

So the request is to return IANA String rather than a named offset when using the { zone_display: 'name' } option.

**Comment by NickStrupat** [comment]
@benshamsian did you find a good solution for this?

**Comment by benshamsian** [comment]
No I did not 
We changed our code to use UTC

**Comment by wcg-developers** [comment]
Hello @benshamsian  and @NickStrupat 

I have a reference for your problem, please check it.
I think it is useful for you.

https://github.com/cyph/phone-number-timezone/blob/master/index.js
