### ISSUE TITLE
Infinte Loop

### ISSUE THREAD

**Issue by benshamsian** [wcg-developers/phone-number-to-timezone#8]
This library goes into an infinite loop for certain area codes. 

Basically any area code that DST is set to true and Start_day is set to false in area_codes.js causes an infinite loop.
I think there are 7 area codes that have the above settings.

Example number: "+98 935 555 9055"
Example Data Set:
{
		name: 'Iran',
		code: '98',
		capital: 'Tehran',
		offset: (3.5),
		dst: true,
		start_month: 2,
		start_week: 21,
		start_offset: false,
		start_day: false,
		end_month: 9,
		end_week: 21,
		end_day: false
},

**Comment by wcg-developers** [comment]
Hello @benshamsian 
We have fixed your issue, so kindly upgrade your package to get the latest updates.
Thank you for your passions.
