### ISSUE TITLE
Incorrect offset for Switzerland Phone numbers

### ISSUE THREAD

**Issue by johnhcody** [wcg-developers/phone-number-to-timezone#9]
Hello, I am using this package to get the timeZone offset based on user's phone numbers. Many of the users are based in Switzerland, and depending on the time of year, the offset is either +1 or +2. During the summer Switzerland observes Central European Summer Time where the time is UTC+2. The rest of the year, it is Central European Time (UTC+1).

Here is the return value from getLocalInfo(+41624815695)

```
{
text: '+41',
options: { military: true, zone_display: 'offset' },
time: {
  zone: 'GMT+2',
  hour: '22',
  mins: '45',
  meridian: false,
  display: '22:45'
},
type: 'country',
country_info: {
  name: 'Switzerland',
  code: '41',
  capital: 'Bern',
  offset: 1,
  dst: true,
  start_month: 2,
  start_week: 4,
  start_offset: false,
  start_day: 0,
  end_month: 9,
  end_week: 4,
  end_day: 0,
  index: 228
},
offset: 1,
dst: true,
location: 'Switzerland',
dstnow: true
}
```

It looks like time.zone reflects the UTC+2, but the offset is 1

**Comment by wcg-developers** [comment]
@johnhcody 
We will check and update the package.

**Comment by wcg-developers** [comment]
@johnhcody 
We have fixed your issue, so kindly upgrade your package to get the latest updates.
Thank you for your passions.
